# Marginalia in the Archive

DISCUSS: Significant works addressing marginalia produced in the early modern period, and the presence of marginalia in both the physical and digital archive (ie materiality)

## The Historiography of Marginalia 

- My project on Dee has taken its place in what is now a substantial series of case stud- ies: these have been devoted either to the marginalia and related notes produced by individual readers (including Gabriel Harvey, Ben Jonson, Inigo Jones, William Blount, William Drake, Michel de Montaigne, Johannes Kepler, and Guillaume Bude ́)5 or to the notes by different readers in multiple copies of a single text (Heidi Brayman Hackel has devoted a chapter to the readers’ marks in 151 copies of Sidney’s Arca- dia, and Heather Jackson to the marginalia in 386 copies of Boswell’s Life of Johnson, while Owen Gingerich has published a best-selling book on his thirty-year hunt for annotations in all of the 600 surviving copies of Copernicus’s De Revolutionibus).

While studying texts of the past, it is not unusual to stumble upon evidence that a document had a ‘life’ before the archive it is currently in; numerous notes throughout the text at the bottom of the page made by the original purchaser, corrections scrawled in rough handwriting from a child using the document as reading practice, or perhaps there is even an initial on the title page left from the document’s first foray into the archive. Indeed, these markings known formally as marginalia not only served a purpose to those who created them, they also serve a purpose for historians through how they may situate a text within its history and allow for a glimpse into the public and private lives of the annotator.

Marginalia have been recognized as significant by scholars since as early as the 19th century, then used as a means to construct the history of earlier scholars in more detail and to expand upon their published works. Particularly of note from this time was literary scholar George Charles Moore Smith’s work. In 1913 he published a book that aimed to "illustrate the life, character, and opinions" of early modern writer Gabriel Harvey using his "unpublished materials", citing Harvey’s vast array of marginalia in this process of extending existing knowledge.[@harvey_gabriel_1913] More current works tend to focus on the materiality of marginalia, using a combination of their content alongside their placement and material features of the book itself to analyze how early modern readers interacted with and used literature.[@acheson_early_2019, 3] 

One of the earlier modern seminal works in the history of reading, ""Studied for Action": How Gabriel Harvey Read His Livy" by historians Lisa Jardine and Anthony Grafton, expand further on the notes produced by Gabriel Harvey to establish marginalia as an intellectual method through microscopic analysis of his annotations inserted into Livy's ancient history of Rome.[@jardine_studied_1990, 36] The article highlights Harvey's active and purposeful approach to reading, characterized by his meticulous marginalia and extensive annotations. Through an analysis of Harvey's notes and markings, Jardine and Grafton reveal how Harvey used Livy's texts as a foundation for his own intellectual pursuits, employing them to shape his ideas, compositions, and refine his own writings.[@jardine_studied_1990, 59] Harvey's annotations not only offer insights into his personal interpretations of Livy's works but also demonstrate his scholarly engagement and his desire to apply the lessons learned from ancient history to contemporary political and cultural contexts. By examining Harvey's reading practices and the ways in which he interacted with Livy's texts, the article sheds light on the active role of early modern scholars in constructing knowledge and engaging with classical literature for practical and intellectual purposes.

Moving beyond the scholar, historian Heidi Brayman Hackel established the foundations of marginalia "as records of reading motivated by cultural, social, theological, and personal inclinations" through shifting the focus from professional scholars such as Harvey to the more casual reader.[@acheson_early_2019, 15] In this defining work on the history of reading, *Reading Material in Early Modern England* seeks to "delineate the asymmertries of early modern English literacies and reading habits and to expand the category of readers to include a greater variety of English people"; Brayman Hackel accompolishes this by offering a comprehensive examination the social, cultural, and intellectual contexts in which reading took place, providing insights into the reading practices of different members of society, including women, artisans, and the elite through the analysis of annotated texts in multiple formats.[@bh_reading_2005, 257] Through extensive research and select case studies ranging from the library of Lady Anne Clifford to unspecificed annotators present in copies of Philip Sidney's *Arcadia*, Brayman Hackel delves into the materiality of texts, investigating the physical aspects of books and how they influenced reading experiences. She explores the use of illustrations, typography, and paratextual elements, demonstrating how these features shaped readers' interactions with the texts. Through further investigation into print culture, the emergence of the printing press, and the significance of libraries, bookshops, and private collections in shaping access to and availability of reading materials, Brayman Hackel also addresses the impact of censorship and the control of reading materials by established institutions such as Oxford's Bodleian Library and the authorities.[@bh_reading_2005, 84, 99] By extension, Brayman Hackel also examines the purposes of reading in early modern England, ranging from religious and moral instruction to entertainment and leisure. Through this exploration, she counters the fiction of "a singular ideal reader ungrounded in place or time" and instead creates "a portrait of an early modern "gentle reader" alongside fragmentary glimpses of multiple readers at single moments in their reading lives."[@bh_reading_2005, 257] Through emphasis on the importance of reading as a cultural and social practice and its impact on knowledge production, relationships, and the formation of early modern English society, *Reading Material in Early Modern England* contributes to our understanding of the broader historical and [cultural] significance of reading during this period, offering valuable insights into the ways in which texts were consumed, understood, and used in early modern English society.

Closely following Brayman Hackel's publication was the release of *Used Books: Marking Readers in Renaissance England* by William H. Sherman; Sherman's work diverged from the case study model Brayman Hackel follows common in the history of reading, in that he chose to focus on collections of annotated books for his case studies rather than on individual readers or books. Through the isolated traces upon which his book rests, Sherman's analyses yield "some larger patterns and a more systematic sense of how a wider group of readers used a wider range of books than in previous accounts of pre-modern marginalia."[@sherman_used_2008, xii] By analyzing the marginalia of readers who left behind "substantial annotations", Sherman uncovers the diverse motivations behind readers' interactions with books, how these marks provide insights into the readers' responses, interpretations, and both private and public connections with the text. Like Brayman Hackel, Sherman explores how these markings can reveal readers' social identities, scholarly disciplines, and cultural values. However, unlike Brayman Hackel, Sherman focuses more of his analysis not only on content of the marginalia, but the materiality of the text which this marginalia is present in, "putting books alongside the other objects...to reconstruct the material, mental, and cultural worlds of our forebears."[@sherman_used_2008, xiv] Throughout the book, he pays close attention to "patterns of use" such as bindings, repairs, and other signs of wear, which offer further clues about the history of ownership, as well as early modern reading habits and the networks of exchange and circulation that facilitated the dissemination of ideas through books. Further, Sherman considered how the trade of "used" books functioned, the availability and affordability of texts, and the significance of book ownership in the cultural and intellectual life of the time, concluding that "Renaissance readers have much to teach us not only about the uses of books in the past but also about attitudes toward books where the past meets the present."[@sherman_used_2008, 151]

Uniting the work of marginalia as records of reading by Brayman Hackel and of material affordance by Sherman is Stephen Orgel, whose *The Reader in the Book: A Study of Spaces and Traces* examines individual acts of reading by examining books in which the text and marginalia are "in intense communication with each other, glossing, correcting, reminding, emphasizing, arguing — cases in which reading constitutes an active and sometimes adversarial engagement with the book."[@orgel_reader_2015, 24] However, in tandem with this Orgel focuses more intensely on the book's materiality than Brayman Hackel, here echoing Sherman's work, exploring the physical and conceptual spaces created within books and the traces left there by readers, offering an analysis of how reading practices have evolved across the early modern period. Drawing both upon works that are considered early modern literary classics in the present as well as books that were considered classics in their own time, Orgel delves into the ways in which readers absorb the texts they annotate; the concept of reading as writing. He explores the physicality of books, including their size, format, and design, and how these factors shape the reading and by extension annotating experience. Like Brayman Hackel, *The Reader in the Book* delves into the social and cultural aspects of reading, examining how readers' identities, backgrounds, and personal experiences influence their engagement with literature. Each chapter of Orgel's work considers factors such as gender, class, and education, highlighting the diverse ways in which readers approach and unravelled texts. He joins the discussion of materiality and content through understanding how the book itself was conceptualised during the early modern period; how in the shift from manuscript to print culture, the book became not simply a text, but a place and property, and by extension of this, how the goal of printing was not exact replication of an original text but dissemination.[@orgel_reader_2015, 5, 10] Woven throughout Orgel's book is also a timeline of the historical evolution of reading practices, from manuscript culture to the advent of printing and the digital age. Orgel ultimately offers comprehensive analysis of how changes in reading technologies and the dissemination of texts have shaped the book and reader's role over time.

Although not explicitly dealing with the study of marginalia as previously mentioned works have Juliet Fleming's work on material affordances particular to the book and the pen, packaged in her comprehensive book *Cultural Graphology: Writing after Derrida*, is considered key in understanding the annotation of texts as not just acts of reading, but as writing "which is material, which has the power to invent things (including selves), and which exists at the intersection of generic norms and technological affordances."[@acheson_early_2019, 4] As the title of her book indicates, Fleming accomplishes this by expanding on the notion of "cultural graphology" that Jacques Derrida loosely proposes in his work, *Grammatology*, which examines the relationship between writing practices, materiality, and cultural contexts. Fleming engages with Derrida's deconstructionist approach and expands upon his ideas to analyze the ways in which writing functions as a cultural and social practice through the lens of the writing culture in early modern England, particularly as it came to be influenced by the commercial development of print.[@fleming_cultural_2016, 28] She investigates the materiality of writing, including handwriting, typography, and inscriptions, to [unveil the hidden meanings and cultural significance embedded within written texts]. By examining the dynamics of writing within cultural contexts, Fleming challenges the idea that writing is a neutral tool for communication. She explores how writing practices are shaped by cultural and historical factors, emphasizing the multiplicity of meanings and interpretations that emerge from written texts. Especially relevant to the discussion of marginalia is Fleming's conceptualization of the "renaissance collage" which describes the reading undertaken in this period with scissors and knives, through the cutting of the page and associated processes of sewing, stitching, gluing, and filing.[@acheson_early_2019, 35] She categorises the act of cutting books with reasons such as "to remove proscribed or offensive material from prayer books and primers, to obviate the labor of copying in producing commonplace books and other compilations, to reformat texts in order to rationalize the material they contained, to provide room for marginal or other commentaries, to add other material to and thereby expand a given text, to organize their own researches, and to illustrate or embellish presentation and other manuscripts with motifs cut from printed sources," thus establishing this form of readers' traces not as not just the organization of written information, but also as an act of writing. For Fleming, "the cut opens, gathers and sorts; it shapes the present and introduces the future" akin to how historians of reading posit marginalia is used; cutting is not destructive, but rather a means to grow the work being interacted with. Through her exploration of cultural graphology, Fleming invites readers, and in particular, historians of reading and the book, to critically engage with the complexities of writing as a cultural practice. She highlights the significance of materiality, historical context, and philosophical underpinnings in understanding the role of writing in shaping and reflecting cultural and social dynamics.

-----

Marginalia have been recognized as significant by scholars since as early as the 19th century, then used as a means to construct the history of earlier scholars in more detail and to expand upon their published works. Particularly of note from this time was literary scholar George Charles Moore Smith’s work. In 1913 he published a book that aimed to "illustrate the life, character, and opinions" of early modern writer Gabriel Harvey using his "unpublished materials", citing Harvey’s vast array of marginalia in this process of extending existing knowledge.[@harvey_gabriel_1913] More current works tend to focus on the materiality of marginalia, using a combination of their content alongside their placement and material features of the book itself to analyze how early modern readers interacted with and used literature.[@acheson_early_2019, 3] Yet regardless of scope and focus, most studies of marginalia focus on tracing select annotators or on small collections. This is at least partially due to the difficulty finding marginalia across larger collections when these annotations are not prolific and prominent. It is this issue of discoverability which my research project will seek to address.  

## Presence in Physical and Digital Archives
- How is marginalia defined?
  - In each of the archives I used for analysis/training, what counted as marginalia?
    - AOR included both annotations in the margins, as well as the readers' usage of blank pages (nts what did those pages say? ref Wheelocks...)
  - *Used Books* pg 16
  - Jason Scott-Warren and "graffiti"
  - "Marks of active reading (deictics [contextualizing], underlining, summaries, cross-references, queries) [ . . . ] suggest that the book is to be engaged, digested, and re-read. Marks of ownership . . . distinguish a book as a physical object, to be protected, catalogued, inventoried, and valued. Marks of recording (debts, marriages, births, accounts) seem to reside somewhere in between: like ownership marks, they suggest that the book has physical value; like readers ’ marks, they convey that the book is a site of information." --> HBH, 138
    - Yet as Orgel points out, HBH also missed a class of marginalia from this initial classificiation, one that she references in her observations of marginalia present in Sidney's *Arcadia*:
      - "Fragments of verse, lists of clothing, enigmatic phrases, incomplete calculations, sassy records of ownership [ . . . ] a shield painted in watercolors, impish faces peering out from the margin, geometric ﬁ gures on a ﬂ yleaf, a mother and child on a blank sheet [ . . . ] pressed ﬂ owers [ . . . ] the rust outlines of pairs of scissors."
- A large percentage of the annotations he found in literary texts of the sixteenth and seventeenth centuries in the Huntington Library “had no obvious connection with the text they accompanied.” “But,” he continues, they “nonetheless testi ﬁ ed to the place of that book in the reader’s social life, family history, professional practices, political commitments, and devotional rituals.” --> Sherman, Used Books p. xiii. There is also a wonderful miniature history of the subject in Sherman’s John Dee, especially pp. 60 – 78.

In 2008, Sherman wrote in the afterword of *Used Books*:
> Data- bases and facsimiles of the sort described above are primarily concerned with giving us access to accurate and attractive informational content and with helping us to make our way around it (a goal generally known, in the computer and information sciences, as ‘‘usability’’). Their empha- sis on ‘‘interactivity’’ notwithstanding, they have not yet imagined us doing much with or to books beyond turning their pages and have not yet found ways to preserve our marks—much less to improve them or to educate us about the markings of those who turned pages before us.[@sherman_used_2008, 182]


Acheson's book raises a number of historical, cultural, and theoretical questions about books and their readers, many of which could be explored further through greater access to more obscure, both literally and figuratively, research materials such as marginalia. Adam Smyth's contribution to *Early Modern English Marginalia* particularly emphasises this; in his chapter, he sought to identify current traits in recent works on the history of marginalia which bring to the surface a number of questions, paradoxes or gaps, through the analysis of object traces in early modern books.[@acheson_early_2019, 63] These traits-as-problems which Smyth uses to illustrate the value of attending to object traces can also be used to understand the value of integrating machine learning methods, particularly object detection, into the study of marginalia. The history of reading has often revolved around individual readers, even as early modern studies broadly have shifted away from this and towards to the coterie, and, in more recent years, to the network as the unit of cultural analysis.[@acheson_early_2019, 64] This focus on biography has meant that studies of marginalia have tended to connect book annotations back to the individual who created them at the expense of other ways of organizing marginalia, such as by genre. Further expanding on the neglect of genre, the use of biography as the frame for analysing marginalia books has meant that scholars, preoccupied connecting the page marks to the reader's life and identity, have spent less time seeking to establish fundamental histories of the marks themselves, such as where the conventions for marking books came from; in seeking to link marginalia to writing outside of the host text, Smyth posits the questions, "What category of mark or intervention are they? What is the larger group in which they belong?"[@acheson_early_2019, 64] The tether which holds the study of marginalia to biography is at least in part due to the issues of discoverability that marginalia presents. Although more reliably discoverable than the trace object marks which Smyth features in his work, marginalia still demands time to be found whether the host being searched is physical or digital. Finding genre or larger categories which marginalia can be viewed through or belong to require wide reading of numerous sources in order to be defined. The automated detection of marginalia allows for large and diverse corpori to be evaluated for the presence of marginalia with little supervision and more efficiently than a researcher is able to sift through these works manually; following this quick process of identifying marginalia, researchers may then focus on the discovery of genre through analysis of the object detector's output.  

Another trait Smyth identifies in the study of marginalia is the assignment of the reader as "active". Rather than being "passive", readers read with an idea of practical application in their world and the future, "reading as intended to give rise to something else."[@jardine_studied_1990, 30] Smyth refers to the inverse of an active reader, an *inactive* reader, as being found present in unmarked pages, yet I propose an inactive reader could also be defined as one who dismisses the content of the book in favour of its materiality, as something that can be repurposed as a diary or catalogue of debts (cite wigmaker's pages). It is this genre of "inactive" reading that I attempt to find in the following case study using an object detection model applied to the NLS collection of early modern chapbooks printed in Scotland.[@chapbooks] By macroscopely analysing the marginalia of over 3000 works made for popular consumption, trends in how these booklets were used as something more than just entertaining literature can be identified.  




- Acheson's work raises a number of historical, cultural, and theoretical questions about books and their readers, many of which could be explored further through greater access to more obscure, both literally and figuratively, research materials such as marginalia.
  - Existing case studies draw upon specific annotators, since their marginalia is most easily discoverable


-----

Acheson Intro
- 
- Marginalia as a mode –-> set of ways in which material opportunities and practices overlap with intellectual, social, and personal motivations to make meaning in world
- Derrida’s theories about writing --> Consider marginalia, first and foremost, as writing which is material, which has the power to invent things (including selves), and which exists at the intersection of generic norms and technological affordances.
  
Reading Habits and Reading Habitats; or, toward an Ecobibliography of Marginalia- Joshua Calhoun
- Lack of annotation in the early years of e-books is merely a symptom; lack of "annotatability" is the underlying condition. Just as scholars of the future might mistake a lack of annotatability for a lack of interest in annotation, scholars of early modern books tend to speak of books as either annotated or not annotated without considering whether or not the average book in England c. 1600 was annotatable in the first place.
- I wish to point out that scholars tend to assume that the presence of pen and paper equals the potential for written ex- pression.
- Paying attention to sizing—considering its absence and considering its concentration when present—we are likely to no- tice nuances in the archives that we have been missing.

Cut-and-Paste Bookmaking: The Private/Public Agency of Robert Nicolson
- On the other hand, we often find Nicolson engaging in curiously pri- vate practices. One of his trademark habits is to annotate a passage with a barrage of tiny marks, delivered with pinpoint accuracy to particu- lar lines of text: a period here, two periods there, elsewhere a comma or double- or triple-commas, with or without flanking periods, with crosses for points of high excitement (Figure 2.1) --> At least one of these kinds of mark is merely mechanical: Nicolson adds ‘=’ signs to indicate words broken across the line-end by the printer (here again we see the annotator working as the equivalent of a type- setter). 
  - He becomes, in effect, a literary seismograph, offering what looks like a highly personal, line-by-line re- sponse to the rising and falling interest-levels of the text.

Book Marks: Object Traces in Early Modern Books
- These and the other pressed leaves, cuttings and grasses found in books in Cardiff University Special Collections, at the Beinecke in Yale, and elsewhere, are really part of a distinct category of augmented book: the book as collecting space, as box, as cabinet of natural history, the plants carefully assembled by amateur botanists and laid out on the pages. 
- We meet quite frequently the inked flowers added by readers to their books, but these are normally flowers in the form of marginal annota- tions, flowers sketched by hand, evidenced, most canonically, in books owned by Ben Jonson,11 but widespread in general. Such instances of flowers-as-annotations exhibit a twin pull between the functional and the aesthetic. That is, the role of the drawn flower, like the manicule or asterisk, is primarily to mark out a passage of text; but readers seem of- ten to have felt a competing aesthetic impulse to make the flower (or the pointing finger) a vivid, humorous or spectacular intervention. 
- Interpretative pull and push --> the pull to read all marks symbolically, the push that recognizes there is no intent
- ***In an age where full-text dig- ital transcriptions enable near-instantaneous word and phrase searches (a kind of reading that doesn’t always produce good work), object marks present instances of resistance. They demand time in order to be found – and in thus encouraging slow, digressive, wide reading, object traces re- mind us of certain reading methods we would be foolish to abandon.
- One of the problems of histories of reading is always that the ar- chive of reading-as-inwardness is elusive: and so a defining paradox of studies of reading that draw on marginalia is that they are in fact, and necessarily, studies of writing, reflecting on those moments not when readers read, but when readers wrote in books. Of course such moments are often intimately related to reading, but they are not the same, sepa- rated as they must be by at the very least a temporal lag: to make a note is to read and then, some time later, to write. It is thus not surprising that recent work on early modern reading has argued that ideas of use and application are central, and has warned of the perils of conceiving read- ing as romantic interiority: the nature of the marks being studied frames reading as not an internal but an external pursuit.
- ***The close analysis of, typically, a particular reader has meant that the history of read- ing, as a field, has often been organized around biography precisely at a time when early modern studies more generally has been moving away from the individual as the unit of cultural analysis, with a shift in the 1990s and 2000s to the coterie, and, in more recent years, to the network. The dominance of biography and of the individual for histories of book use has meant that studies of marginal anno- tations have tended to link book annotations back to the marking individual at the expense of other ways of organizing marginalia, such as genre (see below), either by reading the marks as expressions of selfhood ("even the most routine marking of a text allows us to hear the voice of the reader"45), or by connecting the markings to the social or political interests of the reader.46 Studies of objects can be useful because they suspend these biographical assumptions – the mark of an object is less obviously expressive of a reader, and less suited to biographical interpretation – and so encourage other ways of thinking about book use.
- The use of biography as the frame for reading marked books has meant critics, preoccupied with readers’ marks in terms of the reader’s identity or life, have spent less time in establishing where the conventions for marking books come from.
  - It would be profitable to place early modern annotations in relation to particular generic precedents, such as humanist dialogues, pedagogical works, devo- tional forms like the catechism, and autobiographical texts: such placements would helpfully connect the specific marginalia to writing other than the host text. Object marks raise this question of genre and influence in an extreme form: what category of mark or intervention are they? What is the larger group in which they belong?
- The "active" reader. One of the most common arguments in studies of marginal annotations in the early modern period and beyond, is that readers were "active" (or sometimes "radical"), rather than "passive," by which is meant generally that readers marked books in pursuit of their own agenda, that readers read with an idea of practical application in the world, that readers were concerned with future uses of the text rather than with authorial intention or orig- inal significance (with "reading as intended to give rise to some- thing else"),48 that readers were quick to depart from prescribed interpretations.
  - ***Smyth refers to the inverse of an active reader, an inactive reader, as being present in unmarked pages, yet an inactive reader could also be defined as one who dismisses the content of the book in favour of its materiality, as something that can be repurposed as a diary or catalogue of debts (cite wigmaker's pages).
- 