# Creation of an Application to Capture the Metadata of Big Data

The first part involves the further adaptation of an application I created for the International Space Station Archaeology Project (ISSAP) to support the needs of archeologists working on the project.[@chantalmb_issap_2022] The ISSAP version of the application is used to analyze photos taken of the living quarters ISSAP received from the International Space Station. The project sought to understand how astronauts use the space of the habitation modules by tracking the small items of daily use across the station as they appeared and disappeared in photographs.[@graham_recording_2022] The tool I created for ISSAP is a rewritten version of the more general purpose Visual Geometry Group Image Annotator developed at Oxford University; the original tool was not suitable for the project because it could not be used collaboratively and did not have a structure for the automated recording of metadata as annotations are generated.[@dutta_via_2019] In general, image annotators are used when creating applications for computer vision to create training data sets that are trained to recognize items of interest through machine learning models used for detection. The researcher annotates the image, and the machine learning model learns to look for these features which have been marked as important. A side effect of this approach is that the metadata created by the researcher while producing these annotations to train the model with becomes divorced from the original metadata of the images. When considering this in relation to the study of book marginalia, it is equivalent to cutting the marginalia out of the pages and only analyzing those select segments without any thought about the document the marginalia came from.

I seek to expand on the collaboration functionality as well as the ability to import existing metadata from both the archive and directly from the images to be annotated. With this feature, new metadata can be produced alongside the context of the original metadata, allowing for the tool to become not only an image annotator, but also a way to reference and track the creation of training data for machine learning projects. Additionally, all metadata will be searchable, allow for researchers to easily reference specific data points and for scholars to browse the data which formed the output being presented to them.

## Technical Overview
- Svelte/Kit
- Electron
- Openseadragon
- Annotorious 
  - As used by [UCL's MicroPasts](https://crowdsourced.micropasts.org/)

## Process

- Concept of slow annotation --> like current slow fashion/slow creation movement
  - If project can temporally afford it (only needs a small amount of training data or has a large group working on annotation), then metadata to tracking training process to be as comprehensive as possible
  - Cite ISSAP as example of "slow annotation"?

- Applied background in UI development
  - Mapping (verify that this is correct term)
    - MS Paint
    - Excel
  - Home and save button placed reasonable distance apart to reduce risk of accidental clicks

- My Metadata
  - Encourage the user to create structured metadata for their annotations
- Extracted Metadata
  - The pre-existing metadata from the uploaded image
- Annotation metadata columns created 


Home
- User can choose to work in existing project or create new project

New Project
- User uploads collection of images they would like to annotate

Workspace
- File viewer
  - Lists uploaded image files
  - Offers ability to add or remove additional files
- Metadata viewer
  - One tab for automatically extracted data


- From homepage, user is always taken to Workspace
  - If they select "New Project" they are taken to an empty workspace with guidance on how to setup a project
  - If they select "Open Existing Project" they are immediately prompted to open the JSON file

- Deleting annotation on canvas deletes corresponding row --> direct interaction/connection between image and metadata being generated

Limitations
- Larger number of files, larger loading time --> 15000 images takes 5min to load
