--- 
title: "Metadata in the Margins"
author: "Chantal M Brousseau"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [MRE-2023.bib, packages.bib]
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/chicago-fullnote-bibliography-short-title-subsequent.csl
link-citations: yes
favicon: assets/images/favicon.ico
github-repo: ChantalMB/MitM-MRE-2023
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
always_allow_html: yes
---

# Welcome to my MRE

- The GitHub repository for this site: https://github.com/ChantalMB/MRE-MitM-2023
- The GitHub repository for the app: https://github.com/ChantalMB/MRE-RocketAnno
- The GitHub repository for the case study: https://github.com/ChantalMB/MRE-Detecting-Marginalia

## Abstract

In this research essay, along with its associated application and case study, I delve into the transformative impact of digitized cultural heritage collections on emerging research methodologies. I have identified key issues which digitized cultural heritage collections and by extension, institutions, face during this time of rapid technological development, specifically in the realm of machine learning. I address this through the development of an application to situate the data which machine learning models are built on, and further demonstrate the positive impact machine learning has the potential to make on the study of history when used consciously with active effort made towards ethical usage. My research ultimately showcases how machine learning, when applied mindfully and with a dedicated focus on ethical considerations, can bring about beneficial changes in the field of history research.

## Acknowledgements
I would first and foremostly like to express my sincere gratitude to my supervisor, Shawn Graham, for his invaluable guidance, unwavering support, and insightful feedback throughout the course of this research. His expertise and mentorship have been instrumental in shaping the direction and final product of this thesis, and I am truly grateful for the time and effort he dedicated to helping me succeed in my entire time at Carleton.
I am also deeply appreciative of my family and friends, who provided me with the space, encouragement, and understanding I needed during this challenging process. Their consistent belief in me, coupled with the occasional insistence on taking breaks and garden-fresh vegetables, has been a source of strength and motivation, and I am fortunate to have such a remarkable support system.
Finally, a special note of thanks goes to my cats, Peaches and Basil. Peaches, by sitting on me for extended periods of time, often served as a peculiar yet effective reminder to remain focused and committed to my work. Feral kitten Basil, who appeared in the midst of my MRE process on our back porch, was a forceful reminder of the balance between life and studies that I often needed to be reminded of. Their companionship during late-night writing sessions brought a sense of comfort and added a touch of warmth to the occasional solitude of research.



